# Generated by Django 5.1.3 on 2024-12-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='knowledgeLevel',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=15),
        ),
    ]
