# Generated by Django 5.1.3 on 2024-12-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_skills_knowledgelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectimages',
            name='image',
            field=models.ImageField(upload_to='mediaProjects'),
        ),
    ]
