# Generated by Django 5.1.3 on 2024-12-08 06:24

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_projectimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
